#:kivy 1.9.0

<KDGame>:
	
	aTower: a_tower
    color: (1, 1, 1, 1)
    canvas:
        Rectangle:
            
            pos: root.width/2, 0
            size: 10, 10

    Label:
    	font_size: 76
    	color: (0.52,1, 1, 1)
    	text: "Test"
    	pos: root.width/2,root.height-76

    Tower:
    	id: a_tower
    	center: self.parent.center

<Tower>:
	size:50,50
	canvas:
		Rectangle:
			pos: self.pos
			size: self.size